
indent=4
margin=120
always_for_in=true
remove_extra_newlines=true
import_to_using=true
whitespace_in_kwargs=false
format_docstrings=true
join_lines_based_on_source=true
indent_submodule=true
surround_whereop_typeparameters=false
annotate_untyped_fields_with_any=true
yas_style_nesting=false
align_struct_field=true
align_assignment=true
align_conditional=true
align_pair_arrow=true
align_matrix=true
normalize_line_endings="auto"
