name: Benchmark a commit
# Keep this in sync with benchmark_pr.yml

on:
  push:
    branches:
      - main
    tags: ['*']

permissions:
  contents: write

jobs:
    generate_table:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: julia-actions/setup-julia@v2
            - uses: julia-actions/cache@v2
            - name: Extract Package Name from Project.toml
              id: extract-package-name
              run: |
                PACKAGE_NAME=$(grep "^name" Project.toml | sed 's/^name = "\(.*\)"$/\1/')
                echo "::set-output name=package_name::$PACKAGE_NAME"
            - name: Build AirspeedVelocity
              env:
                JULIA_NUM_THREADS: 2
              run: |
                # TODO: cache this build step and skip it if the cache hits (but still receive updates)
                # Lightweight build step, as sometimes the runner runs out of memory:
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.add(;url="https://github.com/MilesCranmer/AirspeedVelocity.jl.git")'
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.build("AirspeedVelocity")'
            - name: Add ~/.julia/bin to PATH
              run: |
                echo "$HOME/.julia/bin" >> $GITHUB_PATH
            - name: Run benchmarks
              run: |
                mkdir results
                benchpkg --add https://github.com/LilithHafner/ChairmarksForAirspeedVelocity.jl ${{ steps.extract-package-name.outputs.package_name }} --rev=$GITHUB_SHA --url=${{ github.event.repository.clone_url }} --bench-on=$GITHUB_SHA --output-dir=results/ --tune
            - name: Create markdown table from benchmarks
              run: |
                benchpkgtable ${{ steps.extract-package-name.outputs.package_name }} --rev=$GITHUB_SHA --input-dir=results/ > table.md
                echo '### Benchmark Results' > body.md
                echo '' >> body.md
                echo '' >> body.md
                cat table.md >> body.md

            - name: Create commit comment
              uses: peter-evans/commit-comment@v4
              with:
                body-path: body.md