name: Benchmark a pull request (2)
# Keep this in sync with benchmark_push.yml

on:
  pull_request:
concurrency:
  # Skip and cancel intermediate builds:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
    generate_plots:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v5
            - uses: julia-actions/setup-julia@v2
            - uses: julia-actions/cache@v2
            - name: Extract Package Name from Project.toml
              id: extract-package-name
              run: |
                PACKAGE_NAME=$(grep "^name" Project.toml | sed 's/^name = "\(.*\)"$/\1/')
                echo "::set-output name=package_name::$PACKAGE_NAME"
            - name: Build AirspeedVelocity
              env:
                JULIA_NUM_THREADS: 2
              run: |
                # TODO: cache this build step and skip it if the cache hits (but still receive updates)
                # Lightweight build step, as sometimes the runner runs out of memory:
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.add(;url="https://github.com/MilesCranmer/AirspeedVelocity.jl.git")'
                julia -e 'ENV["JULIA_PKG_PRECOMPILE_AUTO"]=0; import Pkg; Pkg.build("AirspeedVelocity")'
            - name: Add ~/.julia/bin to PATH
              run: |
                echo "$HOME/.julia/bin" >> $GITHUB_PATH
            - name: Run benchmarks
              run: |
                mkdir results
                benchpkg --add https://github.com/LilithHafner/ChairmarksForAirspeedVelocity.jl ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.pull_request.head.sha}},${{github.event.pull_request.base.sha}}" --url=${{ github.event.repository.clone_url }} --bench-on="${{github.event.pull_request.head.sha}}" --output-dir=results/ --tune
            - name: Divide by Entities
              env:
                RESULTS_DIR: results
              run: |
                julia .github/workflows/divide.jl "$RESULTS_DIR"
            - name: Create markdown table from benchmarks
              run: |
                benchpkgtable ${{ steps.extract-package-name.outputs.package_name }} --rev="${{github.event.pull_request.head.sha}},${{github.event.pull_request.base.sha}}" --input-dir=results/ --ratio > table.md
                echo '### Benchmark Results' > body.md
                echo '' >> body.md
                echo '' >> body.md
                cat table.md >> body.md
                echo '' >> body.md
                echo '' >> body.md
                echo '### Benchmark Plots' >> body.md
                echo 'A plot of the benchmark results have been uploaded as an artifact to the workflow run for this PR.' >> body.md
                echo 'Go to "Actions"->"Benchmark a pull request"->[the most recent run]->"Artifacts" (at the bottom).' >> body.md

            - name: wait
              run: sleep 45

            - name: Find Comment
              uses: peter-evans/find-comment@v4
              id: fcbenchmark
              with:
                issue-number: ${{ github.event.pull_request.number }}
                comment-author: 'github-actions[bot]'
                body-includes: Benchmark Results

            - name: Join Tables
              run: |
                echo '${{ steps.fcbenchmark.outputs.comment-body }}' >> old_body.md
                julia .github/workflows/join_table.jl body.md old_body.md merged_body.md

            - name: Comment on PR
              uses: peter-evans/create-or-update-comment@v5
              with:
                comment-id: ${{ steps.fcbenchmark.outputs.comment-id }}
                issue-number: ${{ github.event.pull_request.number }}
                body-path: merged_body.md
                edit-mode: replace
